### ISSUE TITLE
Unable to copy command

### ISSUE THREAD

**Issue by ShayBox** [snipline/rsyncinator-desktop#2]
Clicking the button with the command doesn't copy the command to clipboard, or make the line selectable, I'm on ArchLinux KDE.

**Comment by acoustep** [comment]
Hi @ShayBox , thanks for reporting this. I've had a colleague test this on Debian and the issue is reproducable there, too. I'll work on a fix for it.

**Comment by acoustep** [comment]
Hi @ShayBox I've tested this fix in Ubuntu, if you could download the newest version (0.2.0) and let me know if you have any issues.

**Comment by ShayBox** [comment]
Works for me :+1:

**Comment by acoustep** [comment]
Great, thanks!
